# Generated by Django 5.2.8 on 2025-11-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctor_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="accounts.specialty",
            ),
        ),
    ]
